// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chainel.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.flow.domain.chainel.ChainEl;
import com.only4play.flow.domain.chainel.dto.creator.ChainElCreatorOrUpdater;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(uses = {GenericEnumMapper.class, DateMapper.class})
public interface ChainElMapper {
    ChainElMapper INSTANCE = Mappers.getMapper(ChainElMapper.class);

    ChainEl dtoToEntity(ChainElCreatorOrUpdater dto);
}
