// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.response;

import com.only4play.common.model.AbstractJpaResponse;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.String;

@Schema
public class NodeResponse extends AbstractJpaResponse {
  @Schema(
      title = "节点id"
  )
  private String nodeId;

  @Schema(
      title = "节点名称"
  )
  private String nodeName;

  @Schema(
      title = "组件类型"
  )
  private String cmpId;

  @Schema(
      title = "节点属性参数"
  )
  private String params;

  @Schema(
      title = "自定义参数"
  )
  private String payload;

  public String getNodeId() {
    return nodeId;
  }

  public void setNodeId(String nodeId) {
    this.nodeId = nodeId;
  }

  public String getNodeName() {
    return nodeName;
  }

  public void setNodeName(String nodeName) {
    this.nodeName = nodeName;
  }

  public String getCmpId() {
    return cmpId;
  }

  public void setCmpId(String cmpId) {
    this.cmpId = cmpId;
  }

  public String getParams() {
    return params;
  }

  public void setParams(String params) {
    this.params = params;
  }

  public String getPayload() {
    return payload;
  }

  public void setPayload(String payload) {
    this.payload = payload;
  }
}
