// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.service;

import java.lang.Long;

import com.only4play.common.model.PageWrapper;
import com.only4play.flow.domain.chain.dto.creator.ChainCreator;
import com.only4play.flow.domain.chain.dto.query.ChainQuery;
import com.only4play.flow.domain.chain.dto.updater.ChainUpdater;
import com.only4play.flow.domain.chain.dto.vo.ChainVO;

import org.springframework.data.domain.Page;

public interface IChainService {
    /**
     * create
     */
    Long createChain(ChainCreator creator);

    /**
     * update
     */
    void updateChain(ChainUpdater updater);

    /**
     * valid
     */
    void validChain(Long id);

    /**
     * invalid
     */
    void invalidChain(Long id);

    /**
     * delete
     */
    void deleteChain(Long id);

    /**
     * findById
     */
    ChainVO findById(Long id);

    /**
     * findByPage
     */
    Page<ChainVO> findByPage(PageWrapper<ChainQuery> query);
}
