// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.service;

import com.only4play.flow.domain.chain.dto.ChainCreateReq;
import com.only4play.flow.domain.chain.dto.ChainQueryReq;
import com.only4play.flow.domain.chain.dto.ChainReleaseReq;
import com.only4play.flow.domain.chain.dto.ChainResp;
import com.only4play.flow.domain.chain.dto.ChainUpdateReq;

import org.springframework.data.domain.Page;

public interface IChainService {
    /**
     * create
     */
    Long createChain(ChainCreateReq req);

    /**
     * update
     */
    void updateChain(ChainUpdateReq req);

    /**
     * release
     */
    void releaseChain(ChainReleaseReq req);

    /**
     * valid
     */
    void validChain(Long id);

    /**
     * invalid
     */
    void invalidChain(Long id);

    /**
     * delete
     */
    void deleteChain(Long id);

    /**
     * findById
     */
    ChainResp findById(Long id);

    /**
     * findByPage
     */
    Page<ChainResp> findByPage(ChainQueryReq req);
}
