// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Data
public class ChainReleaseReq {

    private Long id;

    @Schema(title = "页面json")
    private String frontJson;


}
