// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.dto;

import com.only4play.common.model.Request;

import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class ChainQueryRequest implements Request {
}
