// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.repository;

import com.only4play.flow.domain.cmp.Cmp;
import com.only4play.jpa.support.BaseRepository;
import java.lang.Long;

public interface CmpRepository extends BaseRepository<Cmp, Long> {
}
