// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chainel.repository;

import com.only4play.flow.domain.chainel.ChainEl;
import com.only4play.jpa.support.BaseRepository;

public interface ChainElRepository extends BaseRepository<ChainEl, Long> {}
