// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.util.List;
import java.util.Map;

import com.only4play.common.utils.StreamUtils;
import com.only4play.flow.domain.cmp.dto.vo.CmpParamVO;
import com.only4play.flow.domain.cmp.repository.CmpParamRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class CmpParamServiceImpl implements ICmpParamService {
    private final CmpParamRepository cmpParamRepository;

    @Override
    public Map<String, List<CmpParamVO>> mapCmpParamByCmpId() {
        List<CmpParamVO> cmpParams = StreamUtils.toList(cmpParamRepository.findAll(), CmpParamVO::new);
        return StreamUtils.toGroupMap(cmpParams, CmpParamVO::getCmpId);
    }
}
