// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.util.List;
import java.util.Map;

import com.only4play.common.utils.StreamUtils;
import com.only4play.flow.domain.cmp.dto.vo.CmpParamVO;
import com.only4play.flow.domain.cmp.dto.vo.CmpVO;
import com.only4play.flow.domain.cmp.repository.CmpRepository;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class CmpServiceImpl implements ICmpService {
    private final CmpRepository cmpRepository;
    private final ICmpParamService iCmpParamService;

    @Override
    public List<CmpVO> findCmp() {
        Map<String, List<CmpParamVO>> cmpParamMap = iCmpParamService.mapCmpParamByCmpId();
        return StreamUtils.toList(cmpRepository.findAll(), e -> new CmpVO(e, cmpParamMap.get(e.getCmpId())));
    }

}
