// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.util.List;
import java.util.Map;

import com.only4play.common.utils.StreamUtils;
import com.only4play.flow.domain.cmp.mapper.CmpMapper;
import com.only4play.flow.domain.cmp.repository.CmpRepository;
import com.only4play.flow.domain.cmp.response.CmpParamResp;
import com.only4play.flow.domain.cmp.response.CmpResp;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class CmpServiceImpl implements ICmpService {
    private final CmpRepository cmpRepository;
    private final ICmpParamService iCmpParamService;

    @Override
    public Map<String, List<CmpResp>> findAll() {
        Map<String, List<CmpParamResp>> cmpParamMap = iCmpParamService.mapCmpParamByCmpId();
        List<CmpResp> cmpList = StreamUtils.toList(cmpRepository.findAll(), e -> {
            CmpResp cmpResp = CmpMapper.INSTANCE.entity2Resp(e);
            cmpResp.setParams(cmpParamMap.get(e.getCmpId()));
            return cmpResp;
        });
        return StreamUtils.toGroupMap(cmpList, CmpResp::getMenu);
    }

}
