// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.util.List;

import com.only4play.flow.domain.cmp.dto.vo.CmpVO;


public interface ICmpService {

    List<CmpVO> findCmp();

}
