// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.lang.Long;
import java.util.List;
import java.util.Map;

import com.only4play.flow.domain.cmp.dto.vo.CmpParamVO;

public interface ICmpParamService {

    Map<String, List<CmpParamVO>> mapCmpParamByCmpId();
}
