// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.service;

import java.util.List;
import java.util.Map;

import com.only4play.flow.domain.cmp.response.CmpParamResp;

public interface ICmpParamService {

    Map<String, List<CmpParamResp>> mapCmpParamByCmpId();
}
