// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.flow.domain.cmp.Cmp;
import com.only4play.flow.domain.cmp.response.CmpResp;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(uses = {GenericEnumMapper.class, DateMapper.class})
public interface CmpMapper {
    CmpMapper INSTANCE = Mappers.getMapper(CmpMapper.class);

    CmpResp entity2Resp(Cmp entity);

}
