// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.flow.domain.chain.Chain;
import com.only4play.flow.domain.chain.dto.ChainCreateReq;
import com.only4play.flow.domain.chain.dto.ChainReleaseReq;
import com.only4play.flow.domain.chain.dto.ChainResp;
import com.only4play.flow.domain.chain.dto.ChainUpdateReq;
import com.only4play.flow.domain.chain.dto.creator.ChainCreator;
import com.only4play.flow.domain.chain.dto.updater.ChainUpdater;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(uses = {GenericEnumMapper.class, DateMapper.class})
public interface ChainMapper {
    ChainMapper INSTANCE = Mappers.getMapper(ChainMapper.class);

    Chain creator2Entity(ChainCreator dto);

    ChainUpdater req2Updater(ChainUpdateReq request);

    ChainUpdater req2Updater(ChainReleaseReq request);

    ChainCreator req2Creator(ChainCreateReq request);

    ChainResp entity2Response(Chain entity);

}
