// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chainel.dto.creator;

import java.util.Optional;

import com.only4play.flow.domain.chainel.ChainEl;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ChainElCreatorOrUpdater {

    @Schema(title = "应用名称")
    private String applicationName;

    @Schema(title = "链路id")
    private String chainId;

    @Schema(title = "链路el数据")
    private String elData;

    public void updateChainEl(ChainEl param) {
        Optional.ofNullable(getElData()).ifPresent(v -> param.setElData(v));
    }

}
