// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;

@Schema
public class CmpCreateRequest implements Request {
}
