// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;

@Schema
public class CmpUpdateRequest implements Request {
  private Long id;

  public Long getId() {
    return id;
  }

  public void setId(long id) {
    this.id = id;
  }
}
