// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.service;

import java.util.List;

import com.only4play.flow.domain.node.dto.creator.NodeCreator;


public interface INodeService {

    /**
     * batchCreateNode
     */
    void batchCreateNode(String chainId, List<NodeCreator> creatorList);

}
