// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.service;

import com.only4play.common.model.PageRequestWrapper;
import com.only4play.flow.domain.node.creator.NodeCreator;
import com.only4play.flow.domain.node.query.NodeQuery;
import com.only4play.flow.domain.node.updater.NodeUpdater;
import com.only4play.flow.domain.node.vo.NodeVO;
import java.lang.Long;
import org.springframework.data.domain.Page;

public interface INodeService {
  /**
   * create
   */
  Long createNode(NodeCreator creator);

  /**
   * update
   */
  void updateNode(NodeUpdater updater);

  /**
   * valid
   */
  void validNode(Long id);

  /**
   * invalid
   */
  void invalidNode(Long id);

  /**
   * findById
   */
  NodeVO findById(Long id);

  /**
   * findByPage
   */
  Page<NodeVO> findByPage(PageRequestWrapper<NodeQuery> query);
}
