// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.service;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.exception.BusinessException;
import com.only4play.common.model.PageRequestWrapper;
import com.only4play.flow.domain.node.Node;
import com.only4play.flow.domain.node.creator.NodeCreator;
import com.only4play.flow.domain.node.mapper.NodeMapper;
import com.only4play.flow.domain.node.query.NodeQuery;
import com.only4play.flow.domain.node.repository.NodeRepository;
import com.only4play.flow.domain.node.updater.NodeUpdater;
import com.only4play.flow.domain.node.vo.NodeVO;
import com.only4play.jpa.support.EntityOperations;
import com.querydsl.core.BooleanBuilder;
import java.lang.Long;
import java.lang.Override;
import java.util.Optional;
import java.util.stream.Collectors;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Transactional
@Service
@Slf4j
@RequiredArgsConstructor
public class NodeServiceImpl implements INodeService {
  private final NodeRepository nodeRepository;

  /**
   * createImpl
   */
  @Override
  public Long createNode(NodeCreator creator) {
    Optional<Node> node = EntityOperations.doCreate(nodeRepository)
    .create(() -> NodeMapper.INSTANCE.dtoToEntity(creator))
    .update(e -> e.init())
    .execute();
    return node.isPresent() ? node.get().getId() : 0;
  }

  /**
   * update
   */
  @Override
  public void updateNode(NodeUpdater updater) {
    EntityOperations.doUpdate(nodeRepository)
    .loadById(updater.getId())
    .update(e -> updater.updateNode(e))
    .execute();
  }

  /**
   * valid
   */
  @Override
  public void validNode(Long id) {
    EntityOperations.doUpdate(nodeRepository)
    .loadById(id)
    .update(e -> e.valid())
    .execute();
  }

  /**
   * invalid
   */
  @Override
  public void invalidNode(Long id) {
    EntityOperations.doUpdate(nodeRepository)
    .loadById(id)
    .update(e -> e.invalid())
    .execute();
  }

  /**
   * findById
   */
  @Override
  public NodeVO findById(Long id) {
    Optional<Node> node =  nodeRepository.findById(id);
    return new NodeVO(node.orElseThrow(() -> new BusinessException(CodeEnum.NotFindError)));
  }

  /**
   * findByPage
   */
  @Override
  public Page<NodeVO> findByPage(PageRequestWrapper<NodeQuery> query) {
    BooleanBuilder booleanBuilder = new BooleanBuilder();
    Page<Node> page = nodeRepository.findAll(booleanBuilder,
            PageRequest.of(query.getPage() - 1, query.getPageSize(), Sort.by(
                Sort.Direction.DESC, "createdAt")));
    return new PageImpl<>(page.getContent().stream().map(entity -> new NodeVO(entity))
            .collect(Collectors.toList()), page.getPageable(), page.getTotalElements());
  }
}
