// ---Auto Generated by Only4Play ---
package com.only4play.flow.controller;

import java.util.Map;

import com.only4play.common.constants.CodeEnum;
import com.only4play.common.model.PageResult;
import com.only4play.common.model.PageWrapper;
import com.only4play.common.model.Result;
import com.only4play.flow.domain.chain.creator.ChainCreator;
import com.only4play.flow.domain.chain.mapper.ChainMapper;
import com.only4play.flow.domain.chain.query.ChainQuery;
import com.only4play.flow.domain.chain.request.ChainCreateRequest;
import com.only4play.flow.domain.chain.request.ChainQueryRequest;
import com.only4play.flow.domain.chain.request.ChainUpdateRequest;
import com.only4play.flow.domain.chain.response.ChainResponse;
import com.only4play.flow.domain.chain.service.IChainService;
import com.only4play.flow.domain.chain.updater.ChainUpdater;
import com.only4play.flow.domain.chain.vo.ChainVO;
import com.yomahub.liteflow.core.FlowExecutor;
import com.yomahub.liteflow.flow.FlowBus;
import com.yomahub.liteflow.flow.LiteflowResponse;
import com.yomahub.liteflow.flow.element.Chain;
import com.yomahub.liteflow.flow.element.Node;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("chain/v1")
@RequiredArgsConstructor
public class ChainController {
    private final IChainService chainService;
    private final FlowExecutor flowExecutor;

    /**
     * createRequest
     */
    @PostMapping("createChain")
    public Result<Long> createChain(@RequestBody ChainCreateRequest request) {
        ChainCreator creator = ChainMapper.INSTANCE.request2Creator(request);
        return Result.success(chainService.createChain(creator));
    }

    /**
     * update request
     */
    @PostMapping("updateChain")
    public Result<String> updateChain(@RequestBody ChainUpdateRequest request) {
        ChainUpdater updater = ChainMapper.INSTANCE.request2Updater(request);
        chainService.updateChain(updater);
        return Result.success(CodeEnum.Success.getName());
    }

    /**
     * valid
     */
    @PostMapping("valid/{id}")
    public Result<String> validChain(@PathVariable Long id) {
        chainService.validChain(id);
        return Result.success(CodeEnum.Success.getName());
    }

    /**
     * invalid
     */
    @PostMapping("invalid/{id}")
    public Result<String> invalidChain(@PathVariable Long id) {
        chainService.invalidChain(id);
        return Result.success(CodeEnum.Success.getName());
    }

    /**
     * delete
     */
    @PostMapping("delete/{id}")
    public Result<String> deleteChain(@PathVariable Long id) {
        chainService.deleteChain(id);
        return Result.success(CodeEnum.Success.getName());
    }

    /**
     * findById
     */
    @GetMapping("findById/{id}")
    public Result<ChainResponse> findById(@PathVariable Long id) {
        ChainVO vo = chainService.findById(id);
        ChainResponse response = ChainMapper.INSTANCE.vo2CustomResponse(vo);
        return Result.success(response);
    }

    /**
     * findByPage request
     */
    @PostMapping("findByPage")
    public Result<PageResult<ChainResponse>> findByPage(@RequestBody PageWrapper<ChainQueryRequest> request) {

        Map<String, Chain> chainMap = FlowBus.getChainMap();
        Map<String, Node> nodeMap = FlowBus.getNodeMap();

        LiteflowResponse liteflowResponse = flowExecutor.execute2Resp("c3793dca-661d-46c7-96f6-bc882860e7d2");

        PageWrapper<ChainQuery> pageWrapper = request
                .map(v -> ChainMapper.INSTANCE.request2Query(request.getBean()));
        Page<ChainResponse> page = chainService.findByPage(pageWrapper)
                .map(ChainMapper.INSTANCE::vo2CustomResponse);
        return Result.success(PageResult.of(page.getContent(), page.getTotalElements(),
                                            page.getSize(), page.getNumber()));
    }
}
