// ---Auto Generated by Only4Play ---
package com.only4play.flow.controller;

import java.util.List;
import java.util.Map;

import com.only4play.common.model.Result;
import com.only4play.common.utils.StreamUtils;
import com.only4play.flow.domain.cmp.dto.vo.CmpVO;
import com.only4play.flow.domain.cmp.mapper.CmpMapper;
import com.only4play.flow.domain.cmp.response.CmpResponse;
import com.only4play.flow.domain.cmp.service.ICmpService;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@Slf4j
@RequestMapping("cmp/v1")
@RequiredArgsConstructor
public class CmpController {
    private final ICmpService cmpService;

    /**
     * findCm
     */
    @GetMapping("find")
    public Result<Map<String, List<CmpResponse>>> find() {
        List<CmpVO> cmpList = cmpService.findCmp();
        return Result.success(
                StreamUtils.totoGroupListMap(cmpList, CmpVO::getMenu, CmpMapper.INSTANCE::vo2CustomResponse));
    }

}
