// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.dto.vo;

import java.util.List;

import com.only4play.codegen.processor.vo.AbstractBaseJpaVO;
import com.only4play.flow.domain.cmp.Cmp;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class CmpVO extends AbstractBaseJpaVO {
    @Schema(title = "组件id")
    private String cmpId;

    @Schema(title = "组件名称")
    private String name;

    @Schema(title = "组件形状")
    private String shape;

    @Schema(title = "组件菜单分类")
    private String menu;

    @Schema(title = "组件图标")
    private String svg;

    @Schema(title = "组件背景色")
    private String background;

    @Schema(title = "组件描述")
    private String desc;

    @Schema(title = "组件参数")
    private List<CmpParamVO> params;

    protected CmpVO() {
    }

    public CmpVO(Cmp source, List<CmpParamVO> params) {
        super(source);
        this.setCmpId(source.getCmpId());
        this.setName(source.getName());
        this.setShape(source.getShape());
        this.setMenu(source.getMenu());
        this.setSvg(source.getSvg());
        this.setBackground(source.getBackground());
        this.setDesc(source.getDesc());
        this.setParams(params);
    }

}
