// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.cmp.response;

import com.only4play.common.model.AbstractJpaResponse;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.lang.String;
import java.util.List;

@Schema
@Data
public class CmpResp extends AbstractJpaResponse {
    @Schema(title = "组件id")
    private String cmpId;

    @Schema(title = "组件名称")
    private String name;

    @Schema(title = "组件形状")
    private String shape;

    @Schema(title = "组件菜单分类")
    private String menu;

    @Schema(title = "组件图标")
    private String svg;

    @Schema(title = "组件背景色")
    private String background;

    @Schema(title = "组件描述")
    private String desc;

    @Schema(title = "组件参数")
    private List<CmpParamResp> params;

    public CmpResp(CmpResp cmp,List<CmpParamResp> params){

    }
}
