// ---Auto Generated by Only4Play ---
package com.only4play.flow.application.chain.mapper;

import com.only4play.common.mapper.DateMapper;
import com.only4play.common.mapper.GenericEnumMapper;
import com.only4play.flow.application.chain.dto.ChainCreateRequest;
import com.only4play.flow.application.chain.dto.ChainResponse;
import com.only4play.flow.infrastructure.repository.chain.dataobject.Chain;

import org.mapstruct.Mapper;
import org.mapstruct.factory.Mappers;

@Mapper(uses = { GenericEnumMapper.class, DateMapper.class })
public interface ChainMapper {
    ChainMapper INSTANCE = Mappers.getMapper(ChainMapper.class);

    Chain reqToEntity(ChainCreateRequest dto);

    ChainResponse entityToResp(Chain entity);

}
