// ---Auto Generated by Only4Play ---
package com.only4play.flow.infrastructure.repository.chain;

import com.only4play.flow.infrastructure.repository.chain.dataobject.Chain;
import com.only4play.jpa.support.BaseRepository;
import java.lang.Long;

public interface ChainRepository extends BaseRepository<Chain, Long> {
}
