// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chainel.service;

import com.only4play.flow.domain.chainel.creator.ChainElCreator;
import com.only4play.flow.domain.chainel.dto.creator.ChainElCreatorOrUpdater;

public interface IChainElService {

    /**
     * creatorOrUpdater
     */
    void createOrUpdateChainEl(ChainElCreatorOrUpdater creatorOrUpdater);

}
