// ---Auto Generated by Only4Play ---
package com.only4play.flow.application.chain.dto;

import com.only4play.common.model.Request;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ChainCreateRequest implements Request {
    @Schema(title = "应用名称")
    private String applicationName;

    @Schema(title = "链路id")
    private String chainId;

    @Schema(title = "链路名称")
    private String chainName;

    @Schema(title = "链路描述")
    private String chainDesc;

    @Schema(title = "页面json")
    private String frontJson;

}
