// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.request;

import com.only4play.common.model.Request;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.lang.String;

@Schema
@Data
public class ChainCreateRequest implements Request {
    @Schema(title = "应用名称")
    private String applicationName;

    @Schema(title = "链路id")
    private String chainId;

    @Schema(title = "链路名称")
    private String chainName;

    @Schema(title = "链路描述")
    private String chainDesc;

    @Schema(title = "链路el数据")
    private String elData;

    @Schema(title = "页面json")
    private String frontJson;

    @Schema(title = "有效状态 1-有效,0-失效")
    private Integer validStatus;

}
