// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.dto.creator;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class NodeCreator {

    @Schema(title = "链路id")
    private String chainId;

    @Schema(title = "节点id")
    private String nodeId;

    @Schema(title = "节点名称")
    private String nodeName;

    @Schema(title = "组件id")
    private String cmpId;

    @Schema(title = "节点属性参数")
    private String params;

    @Schema(title = "自定义参数")
    private String payload;
}
