// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.node.request;

import com.only4play.common.model.Request;
import io.swagger.v3.oas.annotations.media.Schema;
import java.lang.Long;
import java.lang.String;

@Schema
public class NodeUpdateRequest implements Request {
    @Schema(title = "节点id")
    private String nodeId;

    @Schema(title = "节点名称")
    private String nodeName;

    @Schema(title = "组件类型")
    private String cmpType;

    @Schema(title = "节点属性参数")
    private String params;

    @Schema(title = "自定义参数")
    private String payload;

    private Long   id;

    public String getNodeId() {
        return nodeId;
    }

    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }

    public String getNodeName() {
        return nodeName;
    }

    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }

    public String getCmpType() {
        return cmpType;
    }

    public void setCmpType(String cmpType) {
        this.cmpType = cmpType;
    }

    public String getParams() {
        return params;
    }

    public void setParams(String params) {
        this.params = params;
    }

    public String getPayload() {
        return payload;
    }

    public void setPayload(String payload) {
        this.payload = payload;
    }

    public Long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }
}
