// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.dto.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ChainQuery {
    @Schema(title = "应用名称")
    private String applicationName;

    @Schema(title = "链路名称")
    private String chainName;
}
