// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.dto.query;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

@Schema
@Data
public class ChainQuery {}
