// ---Auto Generated by Only4Play ---
package com.only4play.flow.domain.chain.repository;

import com.only4play.flow.domain.Chain;
import com.only4play.jpa.support.BaseRepository;
import java.lang.Long;

public interface ChainRepository extends BaseRepository<Chain, Long> {
}
