spring:
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/poseidon?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    generate-ddl: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        format_sql: false