spring:
  application:
    name: op-flow
  datasource:
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/poseidon?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 50
      max-lifetime: 600000
    tomcat:
      test-on-borrow: true
      validation-query: SELECT  1
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    generate-ddl: false
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
        generate_statistics: false
        jdbc:
          batch_size: 1000
        order_inserts: true
        format_sql: false

liteflow:
  rule-source-ext-data-map:
    url: jdbc:mysql://localhost:3306/poseidon?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: root123456
    applicationName: op-flow
    #以下是chain表的配置，这个一定得有
    chainTableName: chain_el
    chainApplicationNameField: application_name
    chainNameField: chain_id
    elDataField: el_data
    #以下是script表的配置，如果你没使用到脚本，下面可以不配置
#    scriptTableName: script
#    scriptApplicationNameField: application_name
#    scriptIdField: script_id
#    scriptNameField: script_name
#    scriptDataField: script_data
#    scriptTypeField: script_type
#    scriptLanguageField: script_language